# -*- coding: utf-8 -*-
"""Censo_eleição2026_1turno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIL1yXjnl0ReivSDobBGLPcyWaK0yi-r

Análise em nível de município, não de eleitor (risco de falácia ecológica)
"""

!pip install requests pandas

# -*- coding: utf-8 -*-
"""
Votos para Presidente - Eleições 2026 (1º turno) - por município e por zona eleitoral
Saídas (em /content/tse2026/):
  - presidente_2026_municipios_long.csv  -> uma linha por município x candidato
  - presidente_2026_municipios_wide.csv  -> uma linha por município, uma coluna por candidato
  - presidente_2026_zonas_long.csv       -> uma linha por município x zona x candidato
  - presidente_2026_resumo_municipios.csv-> eleitorado, comparecimento, brancos, nulos etc.
  - raw/                                 -> JSON bruto de cada município (auditoria/reprocessamento)
"""

import json
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import pandas as pd
import requests
from tqdm.auto import tqdm

# ----------------------------------------------------------------------------
# 1) PARÂMETROS
# ----------------------------------------------------------------------------
CICLO = "ele2026"
ELEICAO = "6257"        # 1º turno federal (Presidente). 2º turno: "6258"
CARGO = "0001"          # Presidente
INCLUIR_EXTERIOR = True # UF "zz" = cidades no exterior
UFS = None              # None = todas; ou lista, ex.: ["sp", "rj"]
THREADS = 8             # reduza se receber erros 403/429
SALVAR_BRUTO = True

BASE = f"https://resultados.tse.jus.br/oficial/{CICLO}/{ELEICAO}"
ELE6 = ELEICAO.zfill(6)
OUT = Path("/content/tse2026") if Path("/content").exists() else Path("tse2026")
RAW = OUT / "raw"
RAW.mkdir(parents=True, exist_ok=True)

sessao = requests.Session()
sessao.headers.update({"User-Agent": "Mozilla/5.0 (pesquisa academica; Colab)"})


# ----------------------------------------------------------------------------
# 2) FUNÇÕES AUXILIARES
# ----------------------------------------------------------------------------
def baixar_json(url, tentativas=4):
    """GET com novas tentativas e espera progressiva. Retorna dict ou None (404)."""
    for i in range(tentativas):
        try:
            r = sessao.get(url, timeout=30)
            if r.status_code == 404:
                return None
            r.raise_for_status()
            return json.loads(r.content.decode("utf-8-sig"))
        except Exception as e:  # noqa: BLE001
            if i == tentativas - 1:
                print(f"FALHA: {url} -> {e}")
                return None
            time.sleep(1.5 * (i + 1))


def num(x):
    """Converte número em formato pt-BR ('1.234' / '12,34') para int/float."""
    if not isinstance(x, str):
        return x
    s = x.strip()
    if s == "":
        return None
    try:
        if "," in s:
            return float(s.replace(".", "").replace(",", "."))
        return int(s.replace(".", ""))
    except ValueError:
        return x


def escalares(d, prefixo=""):
    """Extrai apenas os campos escalares de um dict (com prefixo no nome)."""
    return {f"{prefixo}{k}": num(v) for k, v in d.items()
            if not isinstance(v, (dict, list))}


def mapa_candidatos(no, partido=None, acc=None):
    """Percorre a árvore 'carg' e monta {numero: {nome, partido, sqcand}}."""
    acc = {} if acc is None else acc
    if isinstance(no, dict):
        partido = no.get("sg", partido) if "cand" in no else partido
        if "n" in no and ("nmu" in no or "sqcand" in no):
            acc[str(no["n"])] = {
                "candidato": no.get("nmu") or no.get("nm"),
                "nome_completo": no.get("nm"),
                "partido": partido,
                "sqcand": no.get("sqcand"),
            }
        for v in no.values():
            mapa_candidatos(v, partido, acc)
    elif isinstance(no, list):
        for v in no:
            mapa_candidatos(v, partido, acc)
    return acc


def processar_municipio(m):
    """Baixa o arquivo do município e devolve (linhas_mun, linhas_zona, resumo)."""
    uf, cd = m["uf"], m["cd_tse"]
    url = f"{BASE}/dados/{uf}/{uf}{cd}-c{CARGO}-e{ELE6}-u.json"
    j = baixar_json(url)
    if j is None:
        return [], [], None
    if SALVAR_BRUTO:
        (RAW / f"{uf}{cd}.json").write_text(json.dumps(j, ensure_ascii=False), encoding="utf-8")

    cands = mapa_candidatos(j.get("carg", []))
    ident = {"uf": uf.upper(), "cd_tse": cd, "cd_ibge": m["cd_ibge"], "municipio": m["nome"]}
    lin_mun, lin_zona, resumo = [], [], None

    for a in j.get("abr", []):
        tipo = str(a.get("tpabr", "")).upper()
        geral = escalares(a)
        for bloco in ("s", "e", "v"):          # seções, eleitorado, votos
            if isinstance(a.get(bloco), dict):
                geral.update(escalares(a[bloco], f"{bloco}_"))
        if tipo.startswith("MU"):
            resumo = {**ident, **geral}
        for c in a.get("cand", []):
            n = str(c.get("n"))
            linha = {**ident, "numero": n, **cands.get(n, {}), **escalares(c)}
            if tipo.startswith("MU"):
                lin_mun.append(linha)
            elif tipo.startswith("Z"):
                lin_zona.append({**linha, "zona": a.get("cdabr")})

    # Reserva: se o layout não trouxer 'abr', usa os votos dentro de 'carg'
    if not lin_mun:
        def varrer(no):
            if isinstance(no, dict):
                if "n" in no and "vap" in no:
                    n = str(no["n"])
                    lin_mun.append({**ident, "numero": n, **cands.get(n, {}), **escalares(no)})
                for v in no.values():
                    varrer(v)
            elif isinstance(no, list):
                for v in no:
                    varrer(v)
        varrer(j.get("carg", []))
    return lin_mun, lin_zona, resumo


# ----------------------------------------------------------------------------
# 3) CONFERE O CATÁLOGO DE ELEIÇÕES E LISTA OS MUNICÍPIOS
# ----------------------------------------------------------------------------
cat = baixar_json("https://resultados.tse.jus.br/oficial/comum/config/ele-c.json")
if cat is not None and ELEICAO not in json.dumps(cat):
    print(f"ATENÇÃO: o código {ELEICAO} não aparece em ele-c.json. Confira o catálogo.")

cfg = baixar_json(f"{BASE}/config/mun-e{ELE6}-cm.json")
assert cfg is not None, "Não foi possível baixar a lista de municípios (verifique BASE/ELEICAO)."

municipios = []
for uf in cfg["abr"]:
    sigla = uf["cd"].lower()
    if sigla == "zz" and not INCLUIR_EXTERIOR:
        continue
    if UFS and sigla not in [u.lower() for u in UFS]:
        continue
    for mu in uf.get("mu", []):
        municipios.append({
            "uf": sigla,
            "cd_tse": str(mu["cd"]).zfill(5),
            "cd_ibge": mu.get("cdi"),
            "nome": mu.get("nm"),
        })
print(f"{len(municipios)} localidades a baixar.")

# ----------------------------------------------------------------------------
# 4) DOWNLOAD PARALELO
# ----------------------------------------------------------------------------
L_MUN, L_ZONA, L_RES, falhas = [], [], [], []
with ThreadPoolExecutor(max_workers=THREADS) as ex:
    futuros = {ex.submit(processar_municipio, m): m for m in municipios}
    for f in tqdm(as_completed(futuros), total=len(futuros)):
        a, b, r = f.result()
        if not a:
            falhas.append(futuros[f])
        L_MUN += a
        L_ZONA += b
        if r:
            L_RES.append(r)

# ----------------------------------------------------------------------------
# 5) TABELAS E EXPORTAÇÃO
# ----------------------------------------------------------------------------
df = pd.DataFrame(L_MUN)
dz = pd.DataFrame(L_ZONA)
dr = pd.DataFrame(L_RES)

# 'vap' = votos apurados do candidato; 'pvap' = percentual sobre os votos válidos
df = df.rename(columns={"vap": "votos", "pvap": "pct_validos"})
dz = dz.rename(columns={"vap": "votos", "pvap": "pct_validos"})

df.to_csv(OUT / "presidente_2026_municipios_long.csv", index=False, encoding="utf-8-sig")
dz.to_csv(OUT / "presidente_2026_zonas_long.csv", index=False, encoding="utf-8-sig")
dr.to_csv(OUT / "presidente_2026_resumo_municipios.csv", index=False, encoding="utf-8-sig")

if {"votos", "candidato"}.issubset(df.columns):
    wide = (df.pivot_table(index=["uf", "cd_tse", "cd_ibge", "municipio"],
                           columns="candidato", values="votos", aggfunc="sum")
              .reset_index())
    wide.to_csv(OUT / "presidente_2026_municipios_wide.csv", index=False, encoding="utf-8-sig")

    print("\nTotal nacional reconstruído pela soma dos municípios (conferir com o TSE):")
    tot = df.groupby("candidato")["votos"].sum().sort_values(ascending=False)
    print(pd.DataFrame({"votos": tot, "pct": (100 * tot / tot.sum()).round(2)}))
else:
    print("Layout inesperado. Colunas encontradas:", list(df.columns))
    print("Inspecione um arquivo em", RAW, "e ajuste os nomes dos campos.")

print(f"\nMunicípios com dados: {df['cd_tse'].nunique() if len(df) else 0} | falhas: {len(falhas)}")
if falhas:
    pd.DataFrame(falhas).to_csv(OUT / "falhas.csv", index=False)
    print("Lista de falhas salva em falhas.csv (execute novamente para tentar de novo).")
print("Arquivos em:", OUT)

# Para baixar tudo do Colab em um único .zip, descomente:
# import shutil; from google.colab import files
# shutil.make_archive("/content/tse2026", "zip", OUT); files.download("/content/tse2026.zip")

# 0) INSTALAÇÃO (rode esta célula uma vez; o Colab reinicia o ambiente)
!pip install -q geobr geopandas plotly sidrapy

import geopandas as gpd
import pandas as pd
import plotly.express as px
from geobr import read_municipality

"""

Mapa dinâmico: Censo 2022 x Resultado da Eleição 2026 (Presidente) por município


Pré-requisito: já ter rodado 'votos_presidente_2026_municipios.py' e ter os CSVs
em /content/tse2026/ (ou ajuste CAMINHO_VOTOS abaixo).

Saída: um arquivo HTML interativo (mapa coroplético), pronto para
"""

# ----------------------------------------------------------------------------
# 1) PARÂMETROS
# ----------------------------------------------------------------------------
CAMINHO_VOTOS = "/content/tse2026/presidente_2026_municipios_wide.csv"
ANO_MALHA = 2022                 # malha do IBGE coincidente com o Censo 2022
CANDIDATO_FOCO = None            # None = usa o 1º colocado nacional; ou "NOME_DO_CANDIDATO"
VARIAVEL_CENSO = "renda"         # ver dicionário de tabelas no passo 3

# ----------------------------------------------------------------------------
# 2) MALHA MUNICIPAL (IBGE, via geobr)
# ----------------------------------------------------------------------------
print("Baixando malha municipal do IBGE...")
malha = read_municipality(code_muni="all", year=ANO_MALHA)
malha = malha.rename(columns={"code_muni": "cd_ibge"})
malha["cd_ibge"] = malha["cd_ibge"].astype(str).str[:7]  # código de 7 dígitos padrão IBGE

import requests

cat = requests.get("https://servicodados.ibge.gov.br/api/v3/agregados").json()

# Filtra: pesquisas do Censo Demográfico cujo nome de alguma tabela contenha "rendimento"
for pesquisa in cat:
    if "censo demográfico" in pesquisa["nome"].lower():
        for tabela in pesquisa["agregados"]:
            if "rendimento" in tabela["nome"].lower() and "per capita" in tabela["nome"].lower():
                print(tabela["id"], "-", tabela["nome"])

# ----------------------------------------------------------------------------
# 3) RENDA — Censo 2022, Rendimento do Responsável pelo Domicílio (FTP/IBGE)
# ----------------------------------------------------------------------------
# AVISO METODOLÓGICO (consta nas notas técnicas oficiais do IBGE):
# Esta variável mede a renda de UMA pessoa por domicílio (o responsável),
# não a renda per capita de todos os moradores. O IBGE desaconselha usá-la
# para ranquear/comparar municípios entre si. Usamos aqui por ser o dado
# oficialmente disponível em arquivo direto; mantemos o nome da coluna
# explícito ("responsavel", não "per_capita") para não confundir na análise.

censo_renda = renda_bruta.copy()  # reaproveita o que já foi baixado e lido

censo_renda["cd_ibge"] = censo_renda["CD_MUN"].astype(str).str.zfill(7)
censo_renda = censo_renda.rename(columns={
    "V06004": "renda_media_responsavel",
    "V06006": "renda_mediana_responsavel",
})

# Conversão de vírgula decimal (padrão IBGE) para ponto
for col in ["renda_media_responsavel", "renda_mediana_responsavel"]:
    censo_renda[col] = (
        censo_renda[col].astype(str).str.replace(",", ".", regex=False)
    )
    censo_renda[col] = pd.to_numeric(censo_renda[col], errors="coerce")

censo_renda = censo_renda[["cd_ibge", "renda_media_responsavel", "renda_mediana_responsavel"]].dropna()

print(censo_renda.shape)
censo_renda.head()

"""Análise para 1 só candidado

"""

# ----------------------------------------------------------------------------
# 4) RESULTADO ELEITORAL
# ----------------------------------------------------------------------------
import pandas as pd

CAMINHO_VOTOS = "/content/tse2026/presidente_2026_municipios_wide.csv"
CANDIDATO_FOCO = None  # None = usa o 1º colocado nacional automaticamente

votos = pd.read_csv(CAMINHO_VOTOS, dtype={"cd_ibge": str})
votos["cd_ibge"] = votos["cd_ibge"].str[:7]

colunas_candidatos = [c for c in votos.columns
                       if c not in ("uf", "cd_tse", "cd_ibge", "municipio")]

if CANDIDATO_FOCO is None:
    CANDIDATO_FOCO = votos[colunas_candidatos].sum().idxmax()
    print(f"Candidato definido automaticamente: {CANDIDATO_FOCO}")

votos["total_validos"] = votos[colunas_candidatos].sum(axis=1)
votos["pct_candidato_foco"] = (100 * votos[CANDIDATO_FOCO] / votos["total_validos"]).round(2)

print(votos[["municipio", CANDIDATO_FOCO, "pct_candidato_foco"]].head())

"""Análise para os dois principais candidatos


O que cada coluna nova significa:

pct_lula / pct_flavio_bolsonaro — percentual de cada um sobre o total de votos válidos do município (não dos dois somados, mas de todos os candidatos — assim o número é comparável ao que o TSE divulga).

vencedor_2c — qual dos dois teve mais votos naquele município (não considera os demais candidatos; é só para colorir o mapa de forma binária, se você quiser).

margem_pp — a diferença entre os dois em pontos percentuais; positivo = Lula na frente, negativo = Flávio Bolsonaro na frente. Essa coluna é especialmente útil depois, para um mapa de "intensidade" da vitória (quanto mais vermelho/azul, maior a margem).

"""

# Percentual de cada candidato sobre os votos válidos
votos["pct_lula"] = (100 * votos["LULA"] / votos["total_validos"]).round(2)
votos["pct_flavio_bolsonaro"] = (100 * votos["FLAVIO BOLSONARO"] / votos["total_validos"]).round(2)

# Quem venceu em cada município (só entre esses dois, para visualização)
votos["vencedor_2c"] = votos.apply(
    lambda r: "LULA" if r["LULA"] > r["FLAVIO BOLSONARO"] else "FLAVIO BOLSONARO",
    axis=1
)

# Diferença de pontos percentuais (útil para mapa de "margem de vitória")
votos["margem_pp"] = (votos["pct_lula"] - votos["pct_flavio_bolsonaro"]).round(2)

print(votos[["municipio", "LULA", "FLAVIO BOLSONARO",
             "pct_lula", "pct_flavio_bolsonaro",
             "vencedor_2c", "margem_pp"]].head(10))

# ----------------------------------------------------------------------------
# 5) MALHA MUNICIPAL + JUNÇÃO COM CENSO E VOTOS
# ----------------------------------------------------------------------------
# !pip install -q geobr geopandas
from geobr import read_municipality

malha = read_municipality(code_muni="all", year=2022)
malha = malha.rename(columns={"code_muni": "cd_ibge"})
malha["cd_ibge"] = malha["cd_ibge"].astype(str).str[:7]

base = (
    malha[["cd_ibge", "name_muni", "abbrev_state", "geometry"]]
    .merge(censo_populacao, on="cd_ibge", how="left")
    .merge(censo_renda, on="cd_ibge", how="left")
    .merge(
        votos[["cd_ibge", "municipio", "LULA", "FLAVIO BOLSONARO",
               "pct_lula", "pct_flavio_bolsonaro",
               "vencedor_2c", "margem_pp", "total_validos"]],
        on="cd_ibge", how="left"
    )
)

print(f"Municípios na malha: {len(malha)}")
print(f"Com população:       {base['populacao'].notna().sum()}")
print(f"Com renda:            {base['renda_media_responsavel'].notna().sum()}")
print(f"Com votos:            {base['pct_lula'].notna().sum()}")

base.head()

# ----------------------------------------------------------------------------
# 6) MAPA INTERATIVO — Resultado eleitoral (% Lula x Flávio Bolsonaro)
# ----------------------------------------------------------------------------
import plotly.express as px

base_wgs84 = base.to_crs(4326)  # Plotly exige WGS84 (lat/lon)

fig_votos = px.choropleth(
    base_wgs84,
    geojson=base_wgs84.geometry,
    locations=base_wgs84.index,
    color="margem_pp",
    hover_name="name_muni",
    hover_data={
        "pct_lula": True,
        "pct_flavio_bolsonaro": True,
        "populacao": True,
        "renda_media_responsavel": True,
    },
    color_continuous_scale="RdBu_r",   # vermelho = Lula à frente, azul = Bolsonaro à frente
    color_continuous_midpoint=0,       # 0 = empate técnico
    labels={"margem_pp": "Margem Lula - Bolsonaro (p.p.)"},
    title="Eleições 2026 (1º turno) — Margem Lula x Flávio Bolsonaro, por município",
)
fig_votos.update_geos(fitbounds="locations", visible=False)
fig_votos.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_votos.write_html("/content/mapa_eleicao_2026.html")
fig_votos.show()

# ----------------------------------------------------------------------------
# 7) MAPA INTERATIVO — Variável do Censo (renda do responsável)
# ----------------------------------------------------------------------------
VARIAVEL_MAPA = "renda_media_responsavel"  # troque para "populacao" se preferir

fig_censo = px.choropleth(
    base_wgs84,
    geojson=base_wgs84.geometry,
    locations=base_wgs84.index,
    color=VARIAVEL_MAPA,
    hover_name="name_muni",
    hover_data={
        "pct_lula": True,
        "pct_flavio_bolsonaro": True,
        "populacao": True,
    },
    color_continuous_scale="Viridis",
    labels={VARIAVEL_MAPA: "Renda média do responsável (R$)"},
    title="Censo 2022 — Rendimento médio do responsável pelo domicílio, por município",
)
fig_censo.update_geos(fitbounds="locations", visible=False)
fig_censo.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_censo.write_html("/content/mapa_censo_2022.html")
fig_censo.show()

# ----------------------------------------------------------------------------
# 7) GRÁFICO DE DISPERSÃO — Renda do responsável x % de voto (Lula e Bolsonaro)
# ----------------------------------------------------------------------------
import plotly.express as px

fig_dispersao = px.scatter(
    base_wgs84,
    x="renda_media_responsavel",
    y="pct_lula",
    size="populacao",            # município maior = bolha maior
    color="margem_pp",
    color_continuous_scale="RdBu_r",
    color_continuous_midpoint=0,
    hover_name="name_muni",
    labels={
        "renda_media_responsavel": "Renda média do responsável (R$)",
        "pct_lula": "% de votos válidos em Lula",
        "margem_pp": "Margem Lula - Bolsonaro (p.p.)",
    },
    title="Renda do responsável x % de voto em Lula, por município",
    opacity=0.6,
)
fig_dispersao.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_dispersao.write_html("/content/dispersao_renda_voto.html")
fig_dispersao.show()

"""Cada ponto é um município — você vê a nuvem de dados real, não uma média visual difícil de interpretar.
O tamanho da bolha (população) ajuda a notar se a relação é puxada por poucos municípios grandes ou é um padrão disperso entre muitos municípios pequenos e "olhar só a média" pode enganar.
A cor reforça visualmente o mesmo código do mapa anterior, então os dois gráficos "conversam" entre si.
"""

# ----------------------------------------------------------------------------
# 7b) GRÁFICO DE DISPERSÃO — Renda do responsável x % de voto (Flávio Bolsonaro)
# ----------------------------------------------------------------------------
fig_dispersao_fb = px.scatter(
    base_wgs84,
    x="renda_media_responsavel",
    y="pct_flavio_bolsonaro",
    size="populacao",
    color="margem_pp",
    color_continuous_scale="RdBu_r",
    color_continuous_midpoint=0,
    hover_name="name_muni",
    labels={
        "renda_media_responsavel": "Renda média do responsável (R$)",
        "pct_flavio_bolsonaro": "% de votos válidos em Flávio Bolsonaro",
        "margem_pp": "Margem Lula - Bolsonaro (p.p.)",
    },
    title="Renda do responsável x % de voto em Flávio Bolsonaro, por município",
    opacity=0.6,
)
fig_dispersao_fb.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_dispersao_fb.write_html("/content/dispersao_renda_voto_bolsonaro.html")
fig_dispersao_fb.show()

# ----------------------------------------------------------------------------
# 8) REGRESSÃO MÚLTIPLA — pct_lula ~ renda + população + UF
# ----------------------------------------------------------------------------
# !pip install -q statsmodels
import statsmodels.formula.api as smf
import numpy as np

# Prepara a base para a regressão (sem geometria, sem NaN nas variáveis usadas)
dados_reg = base_wgs84[[
    "pct_lula", "renda_media_responsavel", "populacao", "abbrev_state"
]].dropna().copy()

# População em log: sem isso, São Paulo (11 milhões) dominaria o modelo
# sozinho, e a relação deixaria de refletir o padrão da maioria dos municípios
dados_reg["log_populacao"] = np.log(dados_reg["populacao"])

# Renda em milhares de reais, só para o coeficiente ficar mais legível
dados_reg["renda_mil"] = dados_reg["renda_media_responsavel"] / 1000

modelo = smf.ols(
    "pct_lula ~ renda_mil + log_populacao + C(abbrev_state)",
    data=dados_reg
).fit()

print(modelo.summary())

"""Coeficiente de renda_mil: quanto o % de voto em Lula muda, em média, para cada R$ 1.000 a mais de renda média do responsável — controlando por tamanho do município e por UF. Esse número é o que isola "efeito de renda" de "efeito de ser grande cidade" ou "efeito de estar nesta ou naquela região".

Coeficiente de log_populacao: efeito do tamanho do município, independente da renda.

Os coeficientes de C(abbrev_state): cada UF comparada a uma UF de referência (a primeira em ordem alfabética, por padrão) — isso captura tudo que é "efeito de região" que não é nem renda nem população (cultura política local, por exemplo).

R-squared: quanto da variação do voto entre municípios esse modelo consegue explicar no total.

P>|t| de cada linha: se o efeito é estatisticamente distinguível de zero, dado o tamanho da amostra.


O que o resultado  mostra

R-squared = 0,796 — as variáveis do modelo (renda, população e UF) explicam cerca de 80% da variação do % de voto em Lula entre municípios. É um ajuste bastante alto para dados de ciências sociais — mas isso provavelmente vem majoritariamente da UF (o "efeito de estar em tal estado" é historicamente muito forte na política brasileira), não necessariamente de renda e população. Só veremos isso com certeza quando aparecerem os coeficientes delas.

Os coeficientes de C(abbrev_state) — cada linha mostra a diferença, em pontos percentuais, entre aquela UF e a UF de referência (a primeira em ordem alfabética — provavelmente AC, Acre, que não aparece na lista porque é o "ponto zero" de comparação). Por exemplo: C(abbrev_state)[T.AL] = 28.83 significa que, mantendo renda e população iguais, um município de Alagoas tem, em média, 28,8 pontos percentuais a mais de voto em Lula do que um município equivalente no Acre. O padrão aqui já é visualmente reconhecível: Nordeste (AL, BA, CE, MA, PB, PE, PI) com coeficientes bem altos e positivos; Sul/Centro-Oeste (MS, MT, PR) com coeficientes baixos — isso é o "efeito regional puro" que sobra depois de controlar por renda e população.
"""



"""
## Os dois coeficientes centrais

**`renda_mil = -6.4882`** (p < 0,001, estatisticamente muito significativo)

Para cada **R$ 1.000 a mais** na renda média do responsável pelo domicílio, o `% de voto em Lula` **cai, em média, 6,49 pontos percentuais** — **mantendo o tamanho do município e a UF constantes**. É um efeito negativo, forte e preciso (o intervalo de confiança vai de −6,95 a −6,03, bem estreito).

**`log_populacao = -0.4221`** (p < 0,001, também significativo)

Como a variável está em log, a leitura é um pouco diferente: cada vez que a **população dobra**, o `% de voto em Lula` cai cerca de **0,42 × ln(2) ≈ 0,29 pontos percentuais** — um efeito estatisticamente real, mas **muito menor** na prática do que o de renda.

## O que isso responde, concretamente

Mesmo depois de descontar o "efeito UF" (que, como vimos antes, é enorme, os municípios do Nordeste votam dezenas de pontos a mais em Lula só por estarem ali, independente de renda), **ainda sobra um efeito de renda claro e na direção esperada**: quanto maior a renda média do responsável, menor o voto em Lula, dentro do mesmo estado e do mesmo porte de cidade.

Isso é metodologicamente mais forte do que o que os dois gráficos de dispersão mostraram sozinhos, porque agora sabemos que essa relação **não é só reflexo de "estados ricos votarem diferente de estados pobres"** , ela persiste *dentro* de cada estado.

## O que ainda não podemos dizer (a ressalva de sempre)

Isso continua sendo nível de município — dizemos "municípios mais ricos votam menos em Lula", não "pessoas mais ricas votam menos em Lula". Um município pode ter renda média alta e, ainda assim, abrigar uma distribuição de votantes muito desigual internamente (bairros ricos e pobres votando de formas opostas), isso a regressão em nível municipal, por definição, não enxerga.
"""



"""Análise por cor e raça"""

# ----------------------------------------------------------------------------
# COR/RAÇA E ALFABETIZAÇÃO — Censo 2022, direto do FTP do IBGE
# ----------------------------------------------------------------------------
import pandas as pd
import zipfile
import io
import requests

def baixar_zip_municipio(url_zip):
    resp = requests.get(url_zip, timeout=60)
    zf_local = zipfile.ZipFile(io.BytesIO(resp.content))
    nome_csv = zf_local.namelist()[0]
    with zf_local.open(nome_csv) as f:
        df = pd.read_csv(f, sep=";", encoding="latin-1")
    return df, nome_csv

URL_COR_RACA = (
    "https://ftp.ibge.gov.br/Censos/Censo_Demografico_2022/"
    "Agregados_por_Setores_Censitarios/Agregados_por_Municipio_csv/"
    "Agregados_por_municipios_cor_ou_raca_BR.zip"
)
URL_ALFABETIZACAO = (
    "https://ftp.ibge.gov.br/Censos/Censo_Demografico_2022/"
    "Agregados_por_Setores_Censitarios/Agregados_por_Municipio_csv/"
    "Agregados_por_municipios_alfabetizacao_BR.zip"
)

cor_raca_bruta, nome1 = baixar_zip_municipio(URL_COR_RACA)
alfab_bruta, nome2 = baixar_zip_municipio(URL_ALFABETIZACAO)

print("Cor/raça:", nome1, cor_raca_bruta.shape)
print(cor_raca_bruta.columns.tolist())
print()
print("Alfabetização:", nome2, alfab_bruta.shape)
print(alfab_bruta.columns.tolist())

# ----------------------------------------------------------------------------
# 3d) PROCESSAMENTO — Cor/raça e taxa de alfabetização
# ----------------------------------------------------------------------------

# --- Cor ou raça (variáveis simples, sem cruzamento) ---
censo_cor_raca = cor_raca_bruta.copy()
censo_cor_raca["cd_ibge"] = censo_cor_raca["CD_MUN"].astype(str).str.zfill(7)

censo_cor_raca = censo_cor_raca.rename(columns={
    "V01317": "pop_branca",
    "V01318": "pop_preta",
    "V01319": "pop_amarela",
    "V01320": "pop_parda",
    "V01321": "pop_indigena",
})

col_cor = ["pop_branca", "pop_preta", "pop_amarela", "pop_parda", "pop_indigena"]
censo_cor_raca[col_cor] = censo_cor_raca[col_cor].apply(pd.to_numeric, errors="coerce")

censo_cor_raca["pop_cor_raca_total"] = censo_cor_raca[col_cor].sum(axis=1)
# % de pretos e pardos somados — indicador mais usado na literatura (PNAD/IBGE costuma agregar os dois)
censo_cor_raca["pct_pretos_pardos"] = (
    100 * (censo_cor_raca["pop_preta"] + censo_cor_raca["pop_parda"]) / censo_cor_raca["pop_cor_raca_total"]
).round(2)

censo_cor_raca = censo_cor_raca[["cd_ibge", "pct_pretos_pardos"]].dropna()

# --- Alfabetização (soma das faixas etárias, numerador / denominador) ---
censo_alfab = alfab_bruta.copy()
censo_alfab["cd_ibge"] = censo_alfab["CD_MUN"].astype(str).str.zfill(7)

cols_total = [f"V{str(i).zfill(5)}" for i in range(644, 656)]   # 15-19 até 70-79, população total
cols_alfab = [f"V{str(i).zfill(5)}" for i in range(748, 760)]   # mesmas faixas, alfabetizados

for c in cols_total + cols_alfab:
    censo_alfab[c] = pd.to_numeric(censo_alfab[c], errors="coerce")

censo_alfab["pop_15mais"] = censo_alfab[cols_total].sum(axis=1)
censo_alfab["pop_alfabetizada"] = censo_alfab[cols_alfab].sum(axis=1)
censo_alfab["taxa_alfabetizacao"] = (
    100 * censo_alfab["pop_alfabetizada"] / censo_alfab["pop_15mais"]
).round(2)

censo_alfab = censo_alfab[["cd_ibge", "taxa_alfabetizacao"]].dropna()

print("Cor/raça:", censo_cor_raca.shape)
print(censo_cor_raca.head())
print("\nAlfabetização:", censo_alfab.shape)
print(censo_alfab.head())

# ----------------------------------------------------------------------------
# 5) MALHA MUNICIPAL + JUNÇÃO COM CENSO (completo) E VOTOS
# ----------------------------------------------------------------------------
base = (
    malha[["cd_ibge", "name_muni", "abbrev_state", "geometry"]]
    .merge(censo_populacao, on="cd_ibge", how="left")
    .merge(censo_renda, on="cd_ibge", how="left")
    .merge(censo_cor_raca, on="cd_ibge", how="left")
    .merge(censo_alfab, on="cd_ibge", how="left")
    .merge(
        votos[["cd_ibge", "municipio", "LULA", "FLAVIO BOLSONARO",
               "pct_lula", "pct_flavio_bolsonaro",
               "vencedor_2c", "margem_pp", "total_validos"]],
        on="cd_ibge", how="left"
    )
)

print(f"Municípios na malha:  {len(malha)}")
print(f"Com população:        {base['populacao'].notna().sum()}")
print(f"Com renda:             {base['renda_media_responsavel'].notna().sum()}")
print(f"Com cor/raça:          {base['pct_pretos_pardos'].notna().sum()}")
print(f"Com alfabetização:     {base['taxa_alfabetizacao'].notna().sum()}")
print(f"Com votos:             {base['pct_lula'].notna().sum()}")

base_wgs84 = base.to_crs(4326)
base.head()

# ----------------------------------------------------------------------------
#  REGRESSÃO MÚLTIPLA EXPANDIDA
# ----------------------------------------------------------------------------
import statsmodels.formula.api as smf
import numpy as np

dados_reg2 = base_wgs84[[
    "pct_lula", "renda_media_responsavel", "populacao",
    "pct_pretos_pardos", "taxa_alfabetizacao", "abbrev_state"
]].dropna().copy()

dados_reg2["log_populacao"] = np.log(dados_reg2["populacao"])
dados_reg2["renda_mil"] = dados_reg2["renda_media_responsavel"] / 1000

modelo2 = smf.ols(
    "pct_lula ~ renda_mil + log_populacao + pct_pretos_pardos + taxa_alfabetizacao + C(abbrev_state)",
    data=dados_reg2
).fit()

# Mostra só as variáveis de interesse (sem poluir com os 26 coeficientes de UF)
print(modelo2.summary())
print("\n--- Resumo das variáveis de interesse ---")
print(modelo2.params[["renda_mil", "log_populacao", "pct_pretos_pardos", "taxa_alfabetizacao"]])
print(modelo2.pvalues[["renda_mil", "log_populacao", "pct_pretos_pardos", "taxa_alfabetizacao"]])
print(f"\nR² do modelo expandido: {modelo2.rsquared:.3f}")
print(f"R² do modelo anterior (sem cor/raça e alfabetização): 0.796")

"""Com a integração da análise de raça e educação, parte do que parecia "efeito de renda" no primeiro modelo era, na verdade, efeito de composição racial e de alfabetização que estava "disfarçado" de renda, porque essas variáveis são correlacionadas entre si no Brasil (municípios com maior % de pretos e pardos tendem a ter renda média mais baixa, por exemplo).

pct_pretos_pardos = +0,26 (p<0,001): cada ponto percentual a mais de população preta+parda está associado a +0,26 p.p. de voto em Lula, mesmo controlando por UF — ou seja, isso não é só "efeito Nordeste", é um padrão que se sustenta dentro de cada estado.

taxa_alfabetizacao = −0,72 (p<0,001): cada ponto percentual a mais na taxa de alfabetização está associado a −0,72 p.p. de voto em Lula. Esse sinal pode parecer contraintuitivo à primeira vista , mas é preciso entender que a alfabetização correlaciona com urbanização, estrutura etária, e outras variáveis fora do modelo, então esse coeficiente pode estar, ele também, "emprestando" efeito de algo que ainda não medimos.
"""

# ----------------------------------------------------------------------------
# 9) TESTE DE MULTICOLINEARIDADE — VIF (Variance Inflation Factor)
# ----------------------------------------------------------------------------
# !pip install -q statsmodels
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

# Usa as mesmas variáveis numéricas do modelo expandido (sem UF, que é categórica
# e tratada de outro jeito — VIF é para variáveis contínuas/numéricas)
vars_numericas = ["renda_mil", "log_populacao", "pct_pretos_pardos", "taxa_alfabetizacao"]
X_vif = dados_reg2[vars_numericas].copy()
X_vif = X_vif.assign(const=1)  # VIF exige uma constante na matriz

vif_resultado = pd.DataFrame({
    "variavel": vars_numericas,
    "VIF": [variance_inflation_factor(X_vif.values, i) for i in range(len(vars_numericas))]
}).sort_values("VIF", ascending=False)

print(vif_resultado.to_string(index=False))

# ----------------------------------------------------------------------------
# 10) PAINEL CONSOLIDADO — mapas + gráficos + resumo da regressão
# ----------------------------------------------------------------------------
import pandas as pd

# --- Tabela resumo da regressão (modelo expandido) ---
tabela_regressao = pd.DataFrame({
    "Variável": ["Renda (R$ mil)", "Log população", "% Pretos/Pardos", "Taxa de alfabetização"],
    "Coeficiente": [-3.090, -0.132, 0.260, -0.716],
    "p-valor": ["<0.001", "0.222", "<0.001", "<0.001"],
    "VIF": [2.79, 1.14, 2.15, 2.63],
}).to_html(index=False, border=0, classes="tabela-reg")

# --- Converte cada figura Plotly já existente em HTML embutível ---
html_mapa_votos = fig_votos.to_html(full_html=False, include_plotlyjs="cdn")
html_dispersao_lula = fig_dispersao.to_html(full_html=False, include_plotlyjs=False)
html_dispersao_fb = fig_dispersao_fb.to_html(full_html=False, include_plotlyjs=False)

# --- Monta a página final ---
pagina = f"""
<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<title>Eleições 2026 x Censo 2022 — Painel de Análise</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 0; padding: 0 20px 60px; background: #fafafa; color: #222; }}
  h1 {{ margin-top: 30px; }}
  h2 {{ border-bottom: 2px solid #ccc; padding-bottom: 6px; margin-top: 50px; }}
  nav {{ position: sticky; top: 0; background: #222; padding: 10px 20px; margin: 0 -20px 20px; }}
  nav a {{ color: #fff; margin-right: 20px; text-decoration: none; font-size: 14px; }}
  .secao {{ margin-bottom: 40px; }}
  .nota {{ background: #fff3cd; border-left: 4px solid #d4a017; padding: 10px 14px; font-size: 14px; margin: 10px 0; }}
  table.tabela-reg {{ border-collapse: collapse; margin-top: 10px; }}
  table.tabela-reg th, table.tabela-reg td {{ border: 1px solid #ccc; padding: 6px 12px; text-align: center; font-size: 14px; }}
  table.tabela-reg th {{ background: #eee; }}
</style>
</head>
<body>

<nav>
  <a href="#mapa">Mapa eleitoral</a>
  <a href="#dispersao">Renda x Voto</a>
  <a href="#regressao">Regressão</a>
</nav>

<h1>Eleições 2026 (1º turno) x Censo 2022 — Painel de Análise</h1>
<p>Fontes: TSE (resultados por município), IBGE/Censo 2022 (população, renda do responsável, cor/raça, alfabetização via FTP), malha municipal via geobr.</p>

<div class="secao" id="mapa">
  <h2>1. Mapa eleitoral</h2>
  {html_mapa_votos}
</div>

<div class="secao" id="dispersao">
  <h2>2. Renda do responsável x % de voto</h2>
  {html_dispersao_lula}
  {html_dispersao_fb}
</div>

<div class="secao" id="regressao">
  <h2>3. Regressão múltipla (pct_lula ~ renda + população + cor/raça + alfabetização + UF)</h2>
  <div class="nota">
    R² do modelo: 0,836. Nível de análise: município (não eleitor individual) — risco de falácia ecológica.
    "Rendimento do responsável" não é renda per capita domiciliar (ver nota metodológica do IBGE).
  </div>
  {tabela_regressao}
</div>

</body>
</html>
"""

with open("/content/relatorio_dashboard.html", "w", encoding="utf-8") as f:
    f.write(pagina)

print("Painel salvo em /content/relatorio_dashboard.html")